NRule:
  enable: false
  size: 2
ImageRule:
  enable: false
  keep: false
  images:
    - g1/hello-world
RegexRule:
  enable: false
  keep: false
  pattern:
    - g1/hello-worl
OlderThanGivenDateRule:
  enable: true
  keep: false
  date: "09.03.2021 21:27"
